# Generated by Django 5.2.4 on 2025-09-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Team Member', 'verbose_name_plural': 'Our Team'},
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='role',
            new_name='position',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(upload_to='team_photos/'),
        ),
    ]
