# Generated by Django 5.2.4 on 2025-09-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name_plural': 'Contact Information'},
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='working_hours',
            field=models.CharField(default='Jumatatu - Ijumaa, 8:00AM - 5:00PM', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(max_length=120),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
