# Generated by Django 5.2.4 on 2025-09-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactsubmission_delete_contactmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn')], max_length=50)),
                ('url', models.URLField()),
                ('icon', models.CharField(help_text="FontAwesome class e.g. 'fa fa-facebook'", max_length=100)),
            ],
        ),
    ]
