# Generated by Django 5.2.4 on 2025-09-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='categories',
            field=models.CharField(choices=[('biashara', 'biashara'), ('vikundi', 'vikundi')], default='Select Category', max_length=300),
        ),
    ]
