# Generated by Django 5.2.4 on 2025-09-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='categories',
            field=models.CharField(choices=[('biashara', 'biashara'), ('vikundi', 'vikundi'), ('nyumba', 'nyumba')], default='Select Category', max_length=300),
        ),
    ]
