# Generated by Django 5.2.4 on 2025-09-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='categories',
            field=models.CharField(choices=[('biashara', 'biashara'), ('vikundi', 'vikundi'), ('nyumba', 'nyumba'), ('waajiriwa', 'waajiriwa'), ('kilimo', 'kilimo')], default='Select Category', max_length=300),
        ),
    ]
