# Generated by Django 5.2.6 on 2025-09-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(default='default-icon.png', max_length=100),
        ),
    ]
