# Generated by Django 5.2.6 on 2025-09-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading for homepage', max_length=200)),
                ('subtitle', models.TextField(help_text='Subtitle or description under heading')),
                ('hero_image', models.ImageField(help_text='Background image for hero section', upload_to='home/')),
                ('button_text', models.CharField(default='Learn More', max_length=50)),
                ('button_link', models.CharField(default='#', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'verbose_name_plural': 'Home Page Content',
            },
        ),
    ]
