# Generated by Django 5.2.6 on 2025-09-17 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_heroslide_delete_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Image Title', max_length=200)),
                ('image', models.ImageField(default='2.jpg', upload_to='gallery/')),
                ('caption', models.TextField(blank=True, default='Image Caption')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['order', '-created_date'],
            },
        ),
        migrations.DeleteModel(
            name='HeroSlide',
        ),
    ]
