# Generated by Django 5.2.4 on 2025-09-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'ordering': ['categories', 'order'], 'verbose_name_plural': 'About Pages'},
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='categories',
            field=models.CharField(choices=[('story', 'Our Story'), ('mission', 'Mission'), ('vision', 'Vision'), ('core_values', 'Core Values'), ('directors', 'Directors'), ('stakeholders', 'Stakeholders'), ('history', 'History'), ('hero_slide', 'Hero Slide')], default='story', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_images/'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
