# Generated by Django 5.2.4 on 2025-09-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_corevalue_director_missionvision_stakeholder_story_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corevalue',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='corevalue',
            name='icon_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='story/'),
        ),
    ]
